### PR TITLE
basic clang integration, can emit llvm

### PR DESCRIPTION
**Pull request by indicatelovelace**
Use `./build/bin/clang --target=picmid -emit-llvm -S $LLVMPIC/Examples/main.c` to try. \
Don't use a manual integer size that is bigger then 8, `int = uint_8`, this will break an assertion.

### CODE REVIEW

**Comment by pr1metine** [comment]
Nice. Could you please link the appropriate issue to this PR? https://docs.github.com/de/enterprise-cloud@latest/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by pr1metine** [comment]
Or at least better describe what this PR achieves

**Review by pr1metine — APPROVED** [review]
LGTM but issue is not done yet

**Comment by pr1metine** [comment]
@handiener your responsibility

**Review by handiener — APPROVED** [review]

**Pull request merged**
